# -*- coding: utf-8 -*-
"""生成澜脉单页演示（自包含 HTML，本地双击即可打开）
数据全部来自已冻结/已落盘的结果文件，页面里注明每块的来源脚本。"""
import pandas as pd, json, base64, os, io
R='results'; D=f'{R}/2026-09-18/dsh'; os.makedirs('demo',exist_ok=True)
def jload(p):
    return json.load(io.open(p,encoding='utf-8'))
frozen=jload(f'{D}/metropt3_metrics_frozen_dsh.json')
pipe=jload(f'{D}/pipeline_summary.json')
mine=frozen['det_best']; cx=jload(f'{R}/2026-09-18/codex/metropt3_ownmodel_unified_primary.json')
alarms=pd.read_csv(f'{D}/pipeline_alarms.csv')
pol=pd.read_csv(f'{D}/decision_policy_v6.csv')
sens=pd.read_csv(f'{D}/decision_sensitivity_v6.csv')
rul=pd.read_csv(f'{R}/2026-09-17/dsh/rul_baseline_metrics.csv')
img=base64.b64encode(open(f'{D}/figures_4in1.png','rb').read()).decode()
D20=f'{R}/2026-09-20/dsh'
bsm1img=base64.b64encode(open(f'{D20}/bsm1_4in1.png','rb').read()).decode()
sd=pd.read_csv(f'{D20}/bsm1_slow_drift_detectors.csv')
rm=pd.read_csv(f'{D20}/bsm1_rul_methods.csv')
db=pd.read_csv(f'{D20}/dual_baseline_bsm1.csv')
sweepimg=base64.b64encode(open(f'{D20}/bsm1_sweep_3in1.png','rb').read()).decode()
sw=pd.read_csv(f'{D20}/bsm1_amp_sweep.csv')
inf=pd.read_csv(f'{D20}/bsm1_influent_robustness.csv')
infimg=base64.b64encode(open(f'{D20}/bsm1_influent_robustness.png','rb').read()).decode()
rs=pd.read_csv(f'{D20}/bsm1_rain_storm.csv')
rsimg=base64.b64encode(open(f'{D20}/bsm1_rain_storm.png','rb').read()).decode()
D21=f'{R}/2026-09-21/dsh'
slimg=base64.b64encode(open(f'{D21}/sludge_line2.png','rb').read()).decode()
swimg=base64.b64encode(open(f'{D21}/sludge_sweep.png','rb').read()).decode()
sdimg=base64.b64encode(open(f'{D21}/sludge_decision.png','rb').read()).decode()
D22=f'{R}/2026-09-22/dsh'
rbdimg=base64.b64encode(open(f'{D22}/bsm2_route_b_detect.png','rb').read()).decode()
rbswimg=base64.b64encode(open(f'{D22}/bsm2_route_b_sweep.png','rb').read()).decode()
rbcimg=base64.b64encode(open(f'{D22}/bsm2_route_b_cond.png','rb').read()).decode()
rbd2img=base64.b64encode(open(f'{D22}/bsm2_route_b_drift.png','rb').read()).decode()
sl=pd.read_csv(f'{D21}/sludge_line2.csv')
rr=pd.read_csv(f'{D20}/bsm1_ratio_rule.csv')
rrimg=base64.b64encode(open(f'{D20}/bsm1_ratio_rule.png','rb').read()).decode()
asum=pd.read_csv(f'{D20}/alarm_strategy_summary.csv')
asimg=base64.b64encode(open(f'{D20}/alarm_strategy.png','rb').read()).decode()
def tbl(df, cols=None, n=None):
    d=df if cols is None else df[cols]
    if n: d=d.head(n)
    h='<table><tr>'+''.join('<th>%s</th>'%c for c in d.columns)+'</tr>'
    for _,r in d.iterrows():
        h+='<tr>'+''.join('<td>%s</td>'%r[c] for c in d.columns)+'</tr>'
    return h+'</table>'
css='''<style>
body{font-family:-apple-system,"Microsoft YaHei",sans-serif;margin:0;background:#f5f7fa;color:#1a2733}
.wrap{max-width:1180px;margin:0 auto;padding:24px}
h1{font-size:24px;margin:0 0 4px}.sub{color:#5b6b7c;font-size:13px;margin-bottom:20px}
.card{background:#fff;border-radius:10px;padding:18px 20px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
h2{font-size:16px;margin:0 0 12px;color:#12507b;border-left:4px solid #12507b;padding-left:8px}
.kpis{display:flex;gap:14px;flex-wrap:wrap}
.kpi{flex:1;min-width:150px;background:#f0f6fb;border-radius:8px;padding:14px}
.kpi .v{font-size:22px;font-weight:600;color:#12507b}.kpi .l{font-size:12px;color:#5b6b7c;margin-top:4px}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{border-bottom:1px solid #e6ecf2;padding:6px 8px;text-align:left}
th{background:#f0f6fb;color:#12507b;font-weight:600}
img{width:100%;border-radius:8px}
.note{font-size:12px;color:#8a97a5;margin-top:8px}
.warn{background:#fff8e6;border-left:4px solid #d99b1f;padding:10px 14px;border-radius:6px;font-size:13px;margin-top:10px}
</style>'''
h=[]
h.append('<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>澜脉 · 演示</title>'+css+'</head><body><div class="wrap">')
h.append('<h1>澜脉 · 污水厂设备预测性维护</h1>')
h.append('<div class="card" style="background:#12507b;color:#fff;font-size:14px"><b>想看仿真的实际效果？</b>双击打开 <b>demo/lanmai_twin.html</b> —— 交互式数字孪生演示台：切换 6 个场景、可拖时间轴/自动播放，看曝气能力退化时模型分数怎么变、第几天报警、第几天真实失效、提前量多少。本页是汇总材料，那一页是可以动手点的演示。</div>')
h.append('<div class="sub">纯软件 · 无硬件改造 · 演示数据来自公开真实工业数据集（SKAB / MetroPT-3 / CWRU / C-MAPSS）与 IWA BSM1 数字孪生仿真｜生成时间 2026-09-20</div>')
h.append('<div class="card"><h2>一、检测：设备健康告警（MetroPT-3 空压机，约 5.8 个月）</h2><div class="kpis">')
h.append('<div class="kpi"><div class="v">%d</div><div class="l">告警事件总数（由结果对象生成，不硬编码）</div></div>'%pipe['检测']['告警数'])
h.append('<div class="kpi"><div class="v">2/4</div><div class="l">及时命中官方故障（timely 召回）</div></div>')
h.append('<div class="kpi"><div class="v">%.4f</div><div class="l">误报事件 / 全稳定小时</div></div>'%mine['fp_per_hour_all_stable'])
h.append('<div class="kpi"><div class="v">%.1f%%</div><div class="l">健康时间被报警占用（TIA-H）</div></div>'%(mine['tia_all_stable']*100))
h.append('<div class="kpi"><div class="v">-8.5 分钟</div><div class="l">命中事件平均提前量</div></div>')
h.append('</div><div class="note">口径：分母为两套独立实现的逐分钟掩码交集；命中判据为告警起点落在故障开始前 60 分钟内或故障窗内。</div>')
h.append('<div class="note"><b>阈值性质：</b>2.3954 是用官方 4 个故障窗按 DET 规则（召回优先、并列取误报最低）选出的工作点，属<b>标签辅助选点</b>；4 个窗同时用于选点与汇报，因此这 2/4 是<b>同集工作点表现，不是独立前瞻验证</b>。无标签 0.995 标定分位工作点为 13.139（timely 0/4、误报 13 次、0.0081 次/全稳定小时）。</div>')
h.append('<div class="warn"><b>诚实说明：</b>MetroPT-3 官方只给了 4 个粗粒度故障区间，召回步长为 25%%，且当前 timely 召回 2/4、约每 8 小时一次误报，<b>尚未达到现场可用水平</b>。这一页展示的是方法与可复现性，不是上线效果。</div></div>')
h.append('<div class="card"><h2>二、双模型对比（同一评价机、同一冻结分母）</h2>')
comp=pd.DataFrame([{'模型':'澜脉（DSH 路线）','建模路线':'工况条件化 + 每日 walk-forward + 最大三个 |z| 的 RMS','timely 召回':'2/4','误报事件':201,'误报/全稳定小时':round(mine['fp_per_hour_all_stable'],4),'TIA-H':round(mine['tia_all_stable'],4)},
 {'模型':'对照（Codex 路线）','建模路线':'三态工况 + 24 小时 walk-forward + 多特征聚合','timely 召回':'2/4','误报事件':cx['false_alarm_events'],'误报/全稳定小时':round(cx['false_alarms_per_all_stable_hour'],4),'TIA-H':round(cx['tia_h_all_stable'],4)}])
h.append(tbl(comp))
h.append('<div class="note">同样抓住 2/4 个故障，澜脉路线的误报事件少 2.8 倍、健康时间被占用少 3 倍。</div></div>')
h.append('<div class="card"><h2>三、告警到建议（前 12 条）</h2>')
h.append(tbl(alarms[['告警起点','持续分钟','峰值分数','诊断','建议窗口','优先级']],n=12))
h.append('<div class="note">建议窗口取该设备"压缩机停机≥30 分钟"的时间段；成本参数为占位值，仅用于结构演示。</div></div>')
h.append('<div class="card"><h2>四、剩余寿命与维护策略（C-MAPSS FD001，100 台）</h2>')
h.append(tbl(rul))
h.append('<div class="note">RUL 为经验模型（逐周期训练、标签按 125 周期截断、测试用官方真值）。MetroPT-3 侧的 RUL 门禁为<b>事后(retrospective)</b>判断，使用了告警时点之后的数据，只能用于「瞬态告警不挂 RUL」的离线结论，不作在线决策依据。</div>')
h.append('<h2 style="margin-top:16px">策略成本对比</h2>'+tbl(pol[['策略','参数','抓住紧急','漏掉紧急','动用非紧急','紧急召回','单台成本']]))
h.append('<div class="note">紧急单元定义：观察窗末真值 RUL ≤ 60 周期（39/100 台）。成本参数为占位值。</div></div>')
h.append('<div class="card"><h2>五、成本敏感性（什么条件下 AI 更划算）</h2>'+tbl(sens))
h.append('<div class="note">行列分别是非计划失效代价与计划更换代价；最后一列是 AI 相对最优固定周期的节省（正数=AI 更省）。需要向企业标定的正是这两个参数。</div></div>')
h.append('<div class="card"><h2>六、关键结果四图</h2><img src="data:image/png;base64,%s">'%img)
h.append('<div class="note">① SKAB 误报-召回曲线 ② 维护策略成本对比 ③ 成本敏感性网格 ④ RUL 预测散点。</div></div>')
h.append('<div class="card"><h2>八、数字孪生闭环：慢退化检测与剩余寿命（BSM1，IWA 标准活性污泥模型）</h2>')
h.append('<img src="data:image/png;base64,%s">'%bsm1img)
h.append('<div class="note">① 退化过程与报警/失效时刻 ② 慢漂移检测方案对照 ③ RUL 方法对照 ④ 冻结参考域选择诊断。全部为仿真数据（15 分钟步长），非现场数据。</div>')
h.append('<h2 style="margin-top:16px">慢漂移检测方案对照（60 天场景，第 20 天起 KLa 衰减 40%）</h2>'+tbl(sd[['方案','阈值','报警时刻','检出延迟','基准误报采样数']]))
h.append('<div class="note">自适应基线把慢漂移逐步纳入「新常态」，因此完全漏检；静态（冻结）基线能检出，且基准运行零误报。</div>')
h.append('<h2 style="margin-top:16px">RUL 方法对照（真值剩余寿命 7.27 天）</h2>'+tbl(rm[['方法','RUL估计','RUL真值','绝对误差']]))
h.append('<div class="note">通用健康指数外推高估 3.8 倍；机理指标（溶解氧）误差 4.0-4.1 天。失效是悬崖式时，RUL 必须挂机理指标。</div>')
h.append('<h2 style="margin-top:16px">双基线并行检测：两条独立通道、各自校准</h2>'+tbl(db))
h.append('<div class="note">MetroPT-3（突变类故障）两通道误报率相近；BSM1 120 天慢漂移中两条独立通道指向同一时刻（40.24 / 40.28 天），健康运行中冻结通道零误报。</div>')
h.append('<h2 style="margin-top:16px">退化幅值-斜率扫描（120 天，6 个场景）</h2>')
h.append('<img src="data:image/png;base64,%s">'%sweepimg)
h.append('<div class="note">① 检出延迟与预警提前量 vs 退化速率 ② 刀锋边缘：健康运行越限 6 点/最长连续 3 点，事件机要求 4 点 ③ 分布位置随严重度单调变化。</div>')
h.append(tbl(sw[['最终KLa比例','斜坡天','检出延迟天','提前量SO3_0_5','提前量SO3_1_0','健康运行误报_自适应','健康运行误报_冻结']]))
h.append('<div class="warn"><b>必须一起看的两条自我限定：</b>① 冻结通道的首报时刻在所有退化场景下都是第 40.3 天，与退化幅值无关 —— 它只能判「有没有异常」，不含严重度信息；② 健康运行越限 6 个样本、最长连续 3 个，事件机要求连续 4 个，「0 误报」与「误报」只差一个采样点，因此 120 天/0 误报是刀锋边缘结果，不能当稳健性结论。对 -60%/100 天及更快的退化，报警不早于曝气功能劣化。</div></div>')
h.append('<h2 style="margin-top:16px">进水工况泛化（三种进水窗口，同一退化配置）</h2>')
h.append('<img src="data:image/png;base64,%s">'%infimg)
h.append(tbl(inf[['工况窗口','健康SO3均值','健康持续低于0_5','健康误报_自适应','健康误报_冻结','检出延迟天','失效前提前量']]))
h.append('<div class="warn"><b>三条要一起看的结论：</b>① 三种工况都检出了退化（无漏检）；② 「120 天 0 误报」只在 A 窗成立（B/C 窗健康运行误报 4 / 3 次），不能用它宣称稳健；③ B、C 窗进水使健康运行 SO3 本底降到 1.01 / 0.61 mg/L，健康运行本身就长期低于 0.5 mg/L 的绝对危险线 —— 绝对阈值判据在该工况下失真，危险线必须按工况自身的健康基线标定。</div>')
h.append('<h2 style="margin-top:16px">雨/暴雨冲击工况（三种进水模式，同一退化配置）</h2>')
h.append('<img src="data:image/png;base64,%s">'%rsimg)
h.append(tbl(rs[['工况','健康误报_自适应','健康误报_冻结','自适应首报','冻结首报','检出延迟天','健康滚动5天中位数','退化滚动5天中位数']]))
h.append('<div class="warn"><b>两个方向要一起看：</b>① 负面：冻结通道健康误报 26 / 18 / 26 次（对照 BSM2 A 窗 0 次），「0 误报」再次被证伪；自适应通道在干天循环与暴雨工况下完全漏检。② 分布位置统计量：健康 1.03 / 2.46 / 6.30 对退化 7.48 / 8.74 / 7.96 —— R1 约 7 倍、R2 约 3.6 倍、<b>R3（含暴雨）只有 1.26 倍</b>，因此它只能当严重度/趋势字段（把它做成报警判据的方案已在下一节被证伪）。</div>')
h.append('<h2 style="margin-top:16px">判据对比：单点事件机 vs 比值判据（12 个工况）</h2>')
h.append('<img src="data:image/png;base64,%s">'%rrimg)
h.append(tbl(rr[['工况','单点事件机_健康误报','健康越限占比_k1.3','检出延迟_k1.3','检出延迟_k1.5','检出延迟_k2.0']]))
h.append('<div class="warn"><b>纠正后的结论（这条是我们自我否证）：</b>真 5 天时间窗下，比值判据在 12 个工况的健康运行上越限占比 <b>0.514–0.948</b>，没有一个为 0；检出延迟中位 25.0 天正好等于评估窗下限 —— 既不特异也不灵敏，<b>作为报警判据不成立</b>，只剩严重度/趋势字段的价值。（初版曾把 5 天窗误写成 7200 点 = 75 天窗，从而得出「零越限」的相反结论，已更正。）</div>')
h.append('<h2 style="margin-top:16px">组合报警策略：上报用并集、派工用与门（12 个工况）</h2>')
h.append('<img src="data:image/png;base64,%s">'%asimg)
h.append(tbl(asum))
h.append('<div class="warn"><b>怎么读修正后的表：</b>① 与门<b>没有实质收益</b>——健康上报 单点 47 / 比值 51 / 并集 98 / 与门 46，与门只降约 2%%；② 并集把上报量翻倍却不多出检出；③ 结论：<b>报警流只用单点事件机</b>（阈值按工况自身健康基线标定），滚动中位数只作为严重度字段随报警附注。</div>')
h.append('<h2 style="margin-top:16px">污泥线闭环：脱水机退化的检出与剩余寿命（路线 A）</h2>')
h.append('<img src="data:image/png;base64,%s">'%slimg)
h.append('<div class="kpis" style="margin-top:10px">')
h.append('<div class="kpi"><div class="v">+55.6%</div><div class="l">湿泥饼产量变化（理论 +55.6%；同刻配对 +52.1%–+55.5%）</div></div>')
h.append('<div class="kpi"><div class="v">1.33 天</div><div class="l">退化后检出延迟（冻结通道）</div></div>')
h.append('<div class="kpi"><div class="v">47.7 天</div><div class="l">相对处置要求失效的提前量</div></div>')
h.append('<div class="kpi"><div class="v">1.00 天</div><div class="l">剩余寿命误差（1 天机理窗）</div></div>')
h.append('</div>')
h.append('<div class="warn"><b>三点必须一起说：</b>① <b>自适应通道在本场景完全漏检</b>（慢漂移被它当成了新常态）→ 双基线并行的必要性又一次在同一物理链上验证；② <b>RUL 的机理拟合窗必须短</b>：同一点 5/2/1 天窗给 273/64/47 天（真值 47.7 天），5 天窗把新斜率与旧平台平均掉了；③ 退化起始若落在投运暂态期（第 20 天），暂态误报会把事件机锁存 → 参考域必须取稳态段。</div>')
h.append('<h2 style="margin-top:16px">污泥线：退化可检测性扫描 + 维护决策（路线 A 续）</h2>')
h.append('<img src="data:image/png;base64,%s">'%swimg)
h.append('<img src="data:image/png;base64,%s" style="margin-top:10px">'%sdimg)
h.append('<div class="kpis" style="margin-top:10px">')
h.append('<div class="kpi"><div class="v">8/8</div><div class="l">首报都在第 61.33 天（与幅值/速率无关）</div></div>')
h.append('<div class="kpi"><div class="v">8/8</div><div class="l">自适应通道漏检（再次证明需双基线）</div></div>')
h.append('<div class="kpi"><div class="v">0–1 天</div><div class="l">机理 RUL 误差（4 个可算真值场景）</div></div>')
h.append('<div class="kpi"><div class="v">-24.5%</div><div class="l">RUL 驱动 vs 最优固定周期（占位成本）</div></div>')
h.append('</div>')
h.append('<div class="warn"><b>两条要一起说：</b>① 首报时刻与退化幅值/速率无关（共同成分主导，第 4 次复现）→ 严重度必须靠机理量与分布位置表达；② 维护决策必须依据 RUL —— 「报警即处置」比 RUL 驱动贵 46%（把 47 天剩余寿命扔掉），而 RUL 驱动相对最优固定周期省 24.5%、非计划失效 0 次。成本参数均为占位值。</div>')
h.append('<h2 style="margin-top:16px">路线 B：BSM2 整厂闭环 + 脱水机退化（2026-09-22）</h2>')
h.append('<img src="data:image/png;base64,%s">'%rbdimg)
h.append('<div class="kpis" style="margin-top:10px">')
h.append('<div class="kpi"><div class="v">0.4 秒/天</div><div class="l">整厂（含 ADM1 消化罐）仿真成本，160 天约 64 秒</div></div>')
h.append('<div class="kpi"><div class="v">109.00 天</div><div class="l">真值失效（与路线 A 完全一致，可比）</div></div>')
h.append('<div class="kpi"><div class="v">86 天</div><div class="l">原始量通道零误报口径检出延迟（晚于失效 37 天）</div></div>')
h.append('<div class="kpi"><div class="v">9.8 天</div><div class="l">设备级比值通道检出延迟（含噪，提前 37.5 天）</div></div>')
h.append('</div>')
h.append('<img src="data:image/png;base64,%s" style="margin-top:10px">'%rbswimg)
h.append('<div class="warn"><b>这一节的价值在「负结果 + 解法」（已由 Codex 批次 5 独立复核，数字逐项一致）：</b>① 本模型/本轨迹/本阈值口径下，5 个原始可测量在整厂尺度<b>未能及时检出</b>这次退化 —— 健康轨迹第 66 天因进水 +23.9% 在 q999 口径下同样告警，所谓「首报」是误报抢跑；零误报口径要 86 天、晚于失效 37 天；② 换成设备级物料平衡比值（干固体产率 / 湿泥饼量 = 含固率，两者都可测）后，在本模型/本列出的噪声结构下<b>相对稳健</b>：健康 0 误报、含噪 9.8 天检出；③ 边界是<b>系统性偏差</b>（周期性日间偏差 3% 时延迟退化到 13–31 天，须配定期标定与趋势校正）；④ 该退化在沼气/能耗/出水上几乎不可见（±0.03%），说明这类故障只能靠设备级量发现。详见 PROJECT_STATE 第 27 节。</div>')
h.append('<h2 style="margin-top:16px">路线 B 补强：现场可用性（进水工况条件化 / 标定漂移）</h2>')
h.append('<img src="data:image/png;base64,%s">'%rbcimg)
h.append('<div class="kpis" style="margin-top:10px">')
h.append('<div class="kpi"><div class="v">34.5 天</div><div class="l">同工况对拍差分：原始量检出（8/8，失效前 14.5 天）</div></div>')
h.append('<div class="kpi"><div class="v">13.4 天</div><div class="l">比值通道检出（8/8，提前 35.6 天）</div></div>')
h.append('<div class="kpi"><div class="v">47 / 73 天</div><div class="l">随机游走漂移 3% / 5% 下的检出延迟（5% 已晚于失效）</div></div>')
h.append('<div class="kpi"><div class="v">唯一有效</div><div class="l">缓解手段＝双测量平均（47→30 天）</div></div>')
h.append('</div>')
h.append('<img src="data:image/png;base64,%s" style="margin-top:10px"> '%rbd2img)
h.append('<div class="warn"><b>两块补强各修掉一个漏洞：</b>① <b>原始量「检不出」被修好</b>——不是靠调阈值（4 个流量箱的条件化仍有 6.16 天的抢跑），而是靠<b>同期同工况对拍差分</b>（日尺度平滑；零分布由健康-健康对拍实测）：原始量从 86 天/晚于失效，变成 34.5 天检出、失效前 14.5 天，比值通道 13.4 天、提前 35.6 天；② <b>标定漂移的边界被钉清</b>：确定性偏差只影响 9–15 天（阈值在含同样偏差的健康段自标定会吸收掉），但<b>随机游走型漂移最危险</b>（3% → 47 天、4/6 检出；5% → 73 天、2/6 检出，已晚于失效）；<b>定期重标定对随机游走无效甚至有害</b>（→76 天、1/6），<b>双测量平均是唯一有效缓解</b>；更要注意：若阈值来自干净标定段，漂移会在 1–7 天内被报成「退化」——那是<b>假 RUL</b>。结论：设备级比值法必须配<b>多源冗余 + 独立漂移监控</b>。详见 PROJECT_STATE 第 29 节。</div>')
h.append('<div class="warn" style="margin-top:8px"><b>收尾验证（2026-09-22 晚）：</b>① <b>跨季节/三相位一致</b>：原始量三个相位都晚于失效（81–86 天），比值通道恒为 <b>9.80 天</b>、对拍差分恒为 12.88 天（4/4）；② <b>漂移边界再确认</b>：无界随机游走 10% → <b>67 天、仅 2/6 检出（已晚于失效）</b>，而均值回归的 AR(1) 5% 只到 20.6 天；③ 对拍差分零分布 4→12 对时延迟 12.9→15.1 天，对外写「约 13–15 天」；④ 冻结前数字总检 27/29 通过（2 项为台账例外）。详见 PROJECT_STATE 第 30 节。</div>')
h.append('<h2 style="margin-top:16px">七条设计原则（均为本项目实验独立得出）</h2>')
h.append('<ul style="font-size:13px;line-height:1.9">')
h.append('<li><b>① 双基线并行：</b>短窗自适应管突变（对慢漂移免疫），冻结基线管慢漂移（对突变不灵敏）；取并集报警并标注来源。</li>')
h.append('<li><b>② RUL 挂机理指标：</b>不要用通用健康指数外推代替机理量。</li>')
h.append('<li><b>③ 冻结参考域必须取自「验收合格且已进入稳态」的历史段：</b>BSM1 第 0-10 天是启动暂态，拿它当参考会让阈值被压到 4.4、健康运行 120 天误报 75 次；改用稳态段（第 30-45 天）后阈值 20.2、误报 0。</li>')
h.append('<li><b>④ 慢漂移的严重度用分布位置统计量（滚动中位数/分位数偏移）或机理指标表达：</b>单点越限的时刻不含严重度信息 —— 6 个退化场景的冻结通道首报都在第 40.3 天，而滚动 5 天中位数随严重度从 1.17 单调升到 5.33。注意它只作严重度字段，把它做成越限报警判据的方案已在第 18.5 节被证伪。</li>')
h.append('<li><b>⑤ 危险/失效阈值按工况自身的健康基线标定（相对劣化幅度），不能用绝对值：</b>换一段进水，健康运行的 SO3 本底就从 1.65 降到 0.61 mg/L，绝对阈值 SO3<0.5 在健康运行中就已经长期成立。</li>')
h.append('<li><b>⑥ RUL 的机理拟合窗必须与被测退化的时标匹配，并带「趋势仍在下降」门控：</b>同一告警点，5/2/1 天窗给 269.25 / 63.30 / <b>46.67</b> 天（真值 47.67 天，事件索引时间窗口径）；含噪（2% 仪表 + 3% 日粒度实验室）下<b>窗长是主要手段</b>：1 天窗误差 26.47 天 → 10 天窗 13.85 天，而 3 日平滑不是（5 天窗反而 18.06→27.92 天）；对已停止下降的场景，线性外推会给出一个不会发生的日期。</li>')
h.append('<li><b>⑦ 设备级退化要用设备自身的物料平衡比值监测：</b>整厂原始量会被进水工况漂移淹没（第 66 天进水 +23.9%，健康轨迹在 q999 口径下同样告警）→ 用「干固体产率 / 湿泥饼量」（= 含固率）这类设备级比值：本模型/本列出的噪声结构下健康 0 误报、含噪 9.8 天检出；<b>边界是系统性偏差</b>（周期性日间偏差 3% → 13–31 天），须配定期标定与趋势校正。</li>')
h.append('</ul>')
h.append('<div class="warn"><b>自我否证清单（保留在材料里，作为方法诚实性的证据）：</b>① 我们提出的「滚动中位数越限判据」在真 5 天窗下不成立（健康运行越限占比 0.51-0.95，无一工况为零）；② 由它派生的「组合与门」在 45 组倍数下都是空操作；③ 消融的两条强结论在无标签标定下 timely 全为 0/4（原 timely 2-3 只在标签辅助阈值 2.395 下成立）；④ 冻结通道的首报时刻与退化幅值/速率无关（三个数据集、四次复现）。这些都已从我们的材料里删除或收窄。</div>')
h.append('<div class="warn"><b>诚实说明：</b>BSM1 为公开标准模型仿真；本节阈值分位、退化幅值与成本参数均为演示设置，未经现场标定。</div></div>')
h.append('<div class="card"><h2>九、数据来源与复现</h2><ul style="font-size:13px;line-height:1.9">')
h.append('<li>SKAB（真实水泵台架）｜ MetroPT-3（地铁空压机，UCI 791）｜ CWRU（轴承故障）｜ C-MAPSS FD001（NASA 涡扇退化）｜ BSM1（IWA 标准活性污泥模型，自建仿真闭环）</li>')
h.append('<li>一键复现：<b>python src/dsh/2026-09-18_14_pipeline.py</b>（检测→诊断→RUL→决策）</li>')
h.append('<li>一致性自检：<b>python src/dsh/2026-09-18_18_consistency_check_v2.py</b></li>')
h.append('<li>局限：四个数据集都来自公开工业设备，与污水厂水泵/鼓风机的工况不同；成本参数未经企业标定；仿真与占位数据均已标注。</li>')
h.append('</ul></div>')
h.append('</div></body></html>')
io.open('demo/lanmai_demo.html','w',encoding='utf-8').write(''.join(h))
print('已生成 demo/lanmai_demo.html  %.0f KB' % (os.path.getsize('demo/lanmai_demo.html')/1024))
print('告警表列：',list(alarms.columns))